name: srinet
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - pytorch-cuda=11.8
  - pyg
  - numpy>=1.21.0
  - pandas>=1.3.0
  - scikit-learn>=1.0.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - tqdm>=4.62.0
  - networkx>=2.6.0
  - scipy>=1.7.0
  - jupyter>=1.0.0
  - ipykernel>=6.0.0
  - plotly>=5.0.0
  - geopandas>=0.10.0
  - folium>=0.12.0
  - pip
  - pip:
    - torch-geometric>=2.3.0